# Generated by Django 2.2.11 on 2021-03-05 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('inside_ip', models.GenericIPAddressField(verbose_name='内网 IP')),
                ('outside_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='外网 IP')),
                ('inside_port', models.IntegerField(default=22, verbose_name='内网端口号')),
                ('outside_port', models.IntegerField(default=52113, verbose_name='外网端口号')),
                ('os', models.CharField(choices=[('CentOS 7', 'CentOS 7'), ('Windows Server 2012', 'Windows Server 20212')], max_length=200, verbose_name='系统')),
                ('cpu', models.IntegerField(choices=[(4, 4), (8, 8), (16, 16), (32, 32)], default=4, verbose_name='CPU 核数')),
                ('memory', models.CharField(choices=[('4G', '4G'), ('8G', '8G'), ('16G', '16G'), ('32G', '32G')], default='8G', max_length=10, verbose_name='内存大小')),
                ('disk', models.CharField(choices=[('100G', '100G'), ('200G', '200G')], default='80G', max_length=10, verbose_name='硬盘大小')),
                ('cloud', models.CharField(choices=[(4, 4), (8, 8), (16, 16), (32, 32)], max_length=200, verbose_name='云平台')),
                ('cloud_user', models.CharField(choices=[('gainhon666', 'gainhon666'), ('lingfannao', 'lingfannao'), ('胡振春221240096', '胡振春221240096'), ('水贝珠宝商业运营管理', '水贝珠宝商业运营管理'), ('zhangtian2018', 'zhangtian2018')], max_length=200, verbose_name='云账号')),
                ('env', models.CharField(choices=[('测试环境', '测试环境'), ('测试环境A', '测试环境A'), ('测试环境B', '测试环境B'), ('生产环境', '生产环境')], default='test', max_length=200, verbose_name='环境')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
