# Generated by Django 2.2.11 on 2021-03-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['name'], 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterField(
            model_name='host',
            name='cloud',
            field=models.CharField(choices=[('阿里云', '阿里云'), ('华为云', '华为云')], max_length=200, verbose_name='云平台'),
        ),
    ]
