# Generated by Django 2.2.11 on 2021-03-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210305_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
