# Generated by Django 2.2.11 on 2021-03-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['env', 'inside_ip'], 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AddField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=200, verbose_name='显示名称名称'),
        ),
    ]
