# Generated by Django 3.2 on 2021-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210420_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='inside_ip',
            field=models.GenericIPAddressField(verbose_name='内网 IP'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together={('inside_ip', 'cloud_user')},
        ),
    ]
