# Generated by Django 3.2 on 2021-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_mysqlinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysqlinstance',
            name='inside_addr',
            field=models.CharField(max_length=200, unique=True, verbose_name='内网地址'),
        ),
    ]
