# Generated by Django 3.2 on 2021-04-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20210427_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['cloud_user', 'env', 'inside_ip'], 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterField(
            model_name='host',
            name='cloud',
            field=models.CharField(max_length=200, verbose_name='云平台'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cloud_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='云账号'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu',
            field=models.IntegerField(default=4, verbose_name='CPU 核数'),
        ),
        migrations.AlterField(
            model_name='host',
            name='disk',
            field=models.CharField(default='80G', max_length=10, verbose_name='硬盘大小'),
        ),
        migrations.AlterField(
            model_name='host',
            name='env',
            field=models.CharField(default='test', max_length=200, verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='host',
            name='memory',
            field=models.CharField(default='8G', max_length=10, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os',
            field=models.CharField(max_length=200, verbose_name='系统'),
        ),
    ]
