# Generated by Django 3.2 on 2021-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210429_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cloud_user',
            field=models.CharField(max_length=200, verbose_name='云账号'),
        ),
    ]
