# Generated by Django 3.2 on 2021-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_alter_host_cloud_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cloud_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='云账号'),
        ),
    ]
