# Generated by Django 3.2 on 2021-05-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_configproject_conf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigProject',
        ),
    ]
