# Generated by Django 3.2 on 2021-05-06 07:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_delete_configproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='环境')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='名称')),
                ('deploy_dir', models.CharField(blank=True, max_length=200, verbose_name='部署路径')),
                ('log_dir', models.CharField(blank=True, max_length=200, verbose_name='日志路径')),
                ('hosts', models.ManyToManyField(blank=True, to='project.Host', verbose_name='主机')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('url', models.URLField(unique=True, verbose_name='地址')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='urls', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '地址大全',
                'verbose_name_plural': '地址大全',
                'ordering': ['project', 'name', 'env'],
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf', models.TextField(verbose_name='配置')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='项目')),
            ],
            options={
                'ordering': ['project'],
            },
        ),
    ]
