# Generated by Django 3.2 on 2021-05-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_env_project_projectconfig_projecturl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectConfig',
            new_name='Config',
        ),
        migrations.RenameModel(
            old_name='ProjectUrl',
            new_name='Url',
        ),
    ]
