# Generated by Django 3.2 on 2021-05-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20210506_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MySQLInstance',
            new_name='MySQL',
        ),
    ]
