# Generated by Django 3.2 on 2021-07-07 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_project_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bh', to='project.host', verbose_name='编译主机'),
        ),
    ]
