# Generated by Django 3.2 on 2021-07-07 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_remove_project_build_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='发布环境')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.host', verbose_name='编译主机')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.project', verbose_name='项目')),
            ],
        ),
    ]
