# Generated by Django 3.2 on 2021-07-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_buildhost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildhost',
            options={'verbose_name': '打包主机', 'verbose_name_plural': '打包主机'},
        ),
        migrations.AlterField(
            model_name='buildhost',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.env', verbose_name='环境'),
        ),
        migrations.AlterField(
            model_name='buildhost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project.host', verbose_name='主机'),
        ),
        migrations.AlterUniqueTogether(
            name='buildhost',
            unique_together={('project', 'env')},
        ),
    ]
