# Generated by Django 3.2 on 2021-07-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20210707_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildhost',
            name='user',
            field=models.CharField(default='www', max_length=200, verbose_name='用户'),
        ),
    ]
