# Generated by Django 3.2 on 2021-07-29 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20210729_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=255, verbose_name='模块名')),
                ('pkg_name', models.CharField(blank=True, max_length=255, verbose_name='包名')),
                ('pkg_type', models.CharField(blank=True, choices=[('jar', 'jar'), ('war', 'war')], max_length=255, verbose_name='包类型')),
                ('port', models.IntegerField(blank=True, verbose_name='端口号')),
                ('deploy_dir', models.CharField(blank=True, max_length=255, verbose_name='部署路径')),
                ('logfile', models.CharField(blank=True, max_length=255, verbose_name='日志文件')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pkg_project', to='project.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目模块',
                'verbose_name_plural': '项目模块',
                'ordering': ['project', 'module'],
                'unique_together': {('project', 'module')},
            },
        ),
    ]
