# Generated by Django 3.2 on 2021-07-30 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_projectmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='popular',
            field=models.BooleanField(default=False, verbose_name='常用的'),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='project.project', verbose_name='项目'),
        ),
    ]
