# Generated by Django 3.2 on 2021-07-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20210730_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='deploy_obj',
        ),
    ]
