# Generated by Django 3.1.13 on 2021-08-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_remove_project_deploy_obj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ['cloud_user', 'env', 'hostname', 'inside_ip'], 'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='projectmodule',
            options={'ordering': ['project', 'pkg_type', 'module'], 'verbose_name': '项目模块', 'verbose_name_plural': '项目模块'},
        ),
    ]
