version: "3.6"

services:
  django:
    image: python:3.8.9
    entrypoint: ["/jsb/entrypoint.sh"]
    volumes:
      - /data/yunwei/jsb:/jsb
    ports:
      - "8000:8000"

  web:
    image: nginx:1.19.10
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/nginx-vhost.conf
      - /data/yunwei:/yunwei
    ports:
      - "80:90"