# Generated by Django 2.2.11 on 2021-02-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_permission', '0002_l1menu_l2menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
