# Generated by Django 2.2.11 on 2021-02-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_permission', '0006_auto_20210224_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部门', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
        migrations.AlterField(
            model_name='l2menu',
            name='name',
            field=models.ForeignKey(blank=True, help_text='绑定模型', limit_choices_to={'app_label__in': ['report']}, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType', verbose_name='模型'),
        ),
    ]
