# Generated by Django 3.2 on 2021-04-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_permission', '0011_alter_userinfo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='auth_permission.department', verbose_name='部门'),
        ),
    ]
