# Generated by Django 3.2 on 2021-07-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_permission', '0017_userinfo_hosted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='hosted_date',
            field=models.DateField(blank=True, null=True, verbose_name='主持日期'),
        ),
    ]
